/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  HyperCoreSystem,
  HyperCoreSystemInterface,
} from "../../contracts/HyperCoreSystem";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract HyperCoreWrite",
        name: "hyperCoreWrite",
        type: "address",
      },
    ],
    name: "setHyperCoreWrite",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x6080806040523460155761010b908161001a8239f35b5f80fdfe6080806040526004361015608a575b36156017575f80fd5b5f546001600160a01b0316803b15608657816064815f9363ad1c3d8b60e01b825233600483015233602483015234604483015234905af18015607b57605857005b67ffffffffffffffff10606757005b634e487b7160e01b5f52604160045260245ffd5b6040513d5f823e3d90fd5b5f80fd5b5f3560e01c63030e8d2003600e573460865760203660031901126086576004356001600160a01b038116908190036086576bffffffffffffffffffffffff60a01b5f5416175f555f80f3fea2646970667358221220ae9a2def4e550e3af4b274f70becff9f207871939c405070aa49206611ee405564736f6c634300081c0033";

type HyperCoreSystemConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: HyperCoreSystemConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class HyperCoreSystem__factory extends ContractFactory {
  constructor(...args: HyperCoreSystemConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      HyperCoreSystem & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): HyperCoreSystem__factory {
    return super.connect(runner) as HyperCoreSystem__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HyperCoreSystemInterface {
    return new Interface(_abi) as HyperCoreSystemInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): HyperCoreSystem {
    return new Contract(address, _abi, runner) as unknown as HyperCoreSystem;
  }
}
