/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { L1Write, L1WriteInterface } from "../../contracts/L1Write";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "_wei",
        type: "uint64",
      },
    ],
    name: "CDeposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "_wei",
        type: "uint64",
      },
    ],
    name: "CWithdrawal",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "asset",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isBuy",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "limitPx",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "sz",
        type: "uint64",
      },
    ],
    name: "IocOrder",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "destination",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "token",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "_wei",
        type: "uint64",
      },
    ],
    name: "SpotSend",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "validator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "_wei",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isUndelegate",
        type: "bool",
      },
    ],
    name: "TokenDelegate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "ntl",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "toPerp",
        type: "bool",
      },
    ],
    name: "UsdClassTransfer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "vault",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isDeposit",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "usd",
        type: "uint64",
      },
    ],
    name: "VaultTransfer",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "_wei",
        type: "uint64",
      },
    ],
    name: "sendCDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "_wei",
        type: "uint64",
      },
    ],
    name: "sendCWithdrawal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "asset",
        type: "uint32",
      },
      {
        internalType: "bool",
        name: "isBuy",
        type: "bool",
      },
      {
        internalType: "uint64",
        name: "limitPx",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "sz",
        type: "uint64",
      },
    ],
    name: "sendIocOrder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "destination",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "token",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "_wei",
        type: "uint64",
      },
    ],
    name: "sendSpot",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "validator",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "_wei",
        type: "uint64",
      },
      {
        internalType: "bool",
        name: "isUndelegate",
        type: "bool",
      },
    ],
    name: "sendTokenDelegate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "ntl",
        type: "uint64",
      },
      {
        internalType: "bool",
        name: "toPerp",
        type: "bool",
      },
    ],
    name: "sendUsdClassTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "vault",
        type: "address",
      },
      {
        internalType: "bool",
        name: "isDeposit",
        type: "bool",
      },
      {
        internalType: "uint64",
        name: "usd",
        type: "uint64",
      },
    ],
    name: "sendVaultTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class L1Write__factory {
  static readonly abi = _abi;
  static createInterface(): L1WriteInterface {
    return new Interface(_abi) as L1WriteInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): L1Write {
    return new Contract(address, _abi, runner) as unknown as L1Write;
  }
}
